# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
      - master
      - development
      - releases/*
        
pool:
  git pull: ubuntu-latest

variables:
  BuildConfiguration: 'Release'

steps:

  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk 3.0.x'
    inputs:
      version: 3.0.x


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.sln'
      arguments: '--configuration $(BuildConfiguration)  /p:Version=0.2.$(Build.BuildID)  /p:PackageVersion=0.2.$(Build.BuildID)'

