# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
      - master
      - development
      - releases/*
      - test

pool:
  git pull: ubuntu-latest

variables:
  BuildConfiguration: 'Release'
  PublishToPublicRepos: eq(variables['build.sourceBranch'], 'refs/heads/master')

steps:

  - task: UseDotNet@2
    displayName: 'Use .Net Core sdk 3.0.x'
    inputs:
      version: 3.0.x


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.sln'
      arguments: '--configuration $(BuildConfiguration)  /p:Version=0.2.$(Build.BuildID)  /p:PackageVersion=0.2.$(Build.BuildID)'



  - task: DotNetCoreCLI@2
    displayName: Run project
    inputs:
      command: run
      projects: 'ConsoleApplication/ConsoleApplication.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-build -pause=off all'


### TODO: PUSH TO GITHUB, if PublishToPublicRepos